volumes:
  db_data:
    driver: local

services:
  app:
    container_name: market-backend
    build: ./environment_development/php/.
    volumes:
      - ./back-end:/var/www/html
    ports:
      - 8080:8080
    command: bun install
    depends_on:
      - db

  db:
    container_name: market-db
    build: environment_development/postgresql/.
    volumes:
      - db_data:/var/lib/postgresql
    environment:
      POSTGRES_DB: market_db
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    ports:
      - 5433:5432

  front:
   container_name: market-frontend
   image: oven/bun:1
   volumes:
     - ./front-end:/home/bun/app
   ports:
     - "3000:3000"
   command: bun run dev --host=0.0.0.0
   depends_on:
     - app