volumes:
  db_data:
    driver: local

services:
  app:
    container_name: market-backend
    build: ./environment_development/php/.
    volumes:
      - ./back-end:/var/www/html
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    container_name: market-db
    build: ./environment_development/mysql/.
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_sql_user
      MYSQL_PASSWORD: my_sql_password
    ports:
      - 3306:3306

  front:
   container_name: market-frontend
   image: oven/bun:1
   volumes:
     - ./front-end:/home/bun/app
   ports:
     - "3000:3000"
   command: bun run dev --host=0.0.0.0
   depends_on:
     - app